In [34]:
from alerce.core import Alerce
import pandas as pd
import pyvo as vo
import requests
import sqlalchemy as sa
import sys
import numpy as np
from astropy.coordinates import SkyCoord
from astropy import units as u

In [35]:
alerce = Alerce()
alerce_tap = vo.dal.TAPService('https://tap.alerce.online/tap')

In [13]:
ztf_objects = alerce.query_objects(
    survey="ztf",
    classifier="lc_classifier",
    class_name="SN",
    format="pandas"
)
print(ztf_objects)

Empty DataFrame
Columns: []
Index: []

In [36]:
ob = alerce.query_object(oid="ZTF26aacextk", survey="ztf", format="pandas")
ob

,oid,ndethist,ncovhist,mjdstarthist,mjdendhist,corrected,stellar,ndet,g_r_max,g_r_max_corr,g_r_mean,g_r_mean_corr,firstmjd,lastmjd,deltajd,meanra,meandec,sigmara,sigmadec,step_id_corr
0,ZTF26aacextk,23,2217,61058.43963,61078.519271,False,False,6,None,None,None,None,61059.56081,61078.519271,18.958461,187.020241,6.967839,0.030032,0.02981,27.5.7a32.dev1

In [37]:
filename = "../Data/tns_search (1).csv"
sources = pd.read_csv(filename)
sources

,ID,Name,RA,DEC,Obj. Type,Redshift,Host Name,Host Redshift,Reporting Group/s,Discovery Data Source/s,...,Discovery Mag/Flux,Discovery Filter,Discovery Date (UT),Sender,Remarks,Unreal,Discovery Bibcode,Classification Bibcodes,Ext. catalog/s,Auto classification
0,207943,SN 2026loz,13:26:37.234,-12:06:11.00,SN Ia,0.141000,NaN,NaN,"GOTO, ZTF","GOTO, ZTF",...,19.9000,L-GOTO,2026-05-07 14:51:45.792,GOTO_bot,NaN,NaN,2026TNSTR1968....1O,2026TNSCR1999....1H,NaN,NaN
1,207922,SN 2026log,15:38:25.317,+02:50:28.66,SN Ia,0.076221,LEDA 1238879,0.07622,"ALeRCE, GOTO, ATLAS","ZTF, GOTO, ATLAS",...,18.7549,g-ZTF,2026-05-07 08:51:56.998,ALeRCE,NaN,NaN,2026TNSTR1964....1M,2026TNSCR2000....1F,NaN,NaN
2,207908,SN 2026lns,13:29:49.691,-05:45:05.96,SN Ia,0.068600,NaN,NaN,"ZTF, GOTO, LAST, ATLAS","ZTF, GOTO, LAST, ATLAS",...,19.2662,r-ZTF,2026-05-07 05:03:27.996,Fritz,NaN,NaN,2026TNSTR1975....1S,NaN,NaN,NaN
3,207886,SN 2026lmw,13:07:35.674,+15:13:24.73,SN Ia,0.077618,NaN,NaN,"ZTF, ATLAS","ZTF, ATLAS",...,19.2447,g-ZTF,2026-05-02 06:00:17.003,Fritz,NaN,NaN,2026TNSTR1975....1S,2026TNSCR2000....1F,NaN,NaN
4,207830,SN 2026lky,12:45:09.372,-35:13:48.39,SN Ia,0.056000,NaN,NaN,"GOTO, ATLAS","GOTO, ATLAS",...,18.7600,L-GOTO,2026-05-05 10:22:43.680,GOTO_bot,NaN,NaN,2026TNSTR1940....1O,2026TNSCR1962....1K,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,206493,SN 2026jqy,17:37:46.128,-00:10:27.29,SN IIn,0.045000,SDSS J173746.12-001028.4,NaN,"ALeRCE, Fink, ATLAS, GOTO","ZTF, ATLAS, GOTO",...,19.9423,r-ZTF,2026-04-15 10:33:17.001,ALeRCE,NaN,NaN,2026TNSTR1627....1M,2026TNSCR1886....1S,NaN,NaN
96,206490,SN 2026jqv,14:18:06.700,+18:27:11.82,SN Ia-pec,0.050000,NaN,NaN,"ATLAS, WFST","ATLAS, WFST",...,18.5930,wide-ATLAS,2026-04-15 02:03:58.176,ATLAS_Bot1,NaN,NaN,2026TNSTR1628....1T,2026TNSCR1816....1S,NaN,NaN
97,206486,SN 2026jqr,15:43:49.397,+30:31:32.48,SN Ia,0.064000,NaN,NaN,"ATLAS, GOTO, ZTF, WFST","ATLAS, GOTO, ZTF, WFST",...,19.3960,wide-ATLAS,2026-04-15 01:42:23.040,ATLAS_Bot1,NaN,NaN,2026TNSTR1628....1T,2026TNSCR1903....1J,NaN,NaN
98,206466,SN 2026jqi,21:35:46.821,-63:54:12.77,SN Ic,0.010300,NaN,NaN,ATLAS,ATLAS,...,18.8080,orange-ATLAS,2026-04-15 09:11:30.336,ATLAS_Bot1,NaN,NaN,2026TNSTR1628....1T,"2026TNSCR1708....1F, 2026TNSCR1723....1S",NaN,NaN
99,206462,SN 2026jqe,16:06:49.916,+32:35:07.82,SN Ia,0.065000,NaN,NaN,"ZTF, ATLAS, GOTO, LAST, Pan-STARRS, YSE","ZTF, ATLAS, GOTO, LAST, Pan-STARRS",...,19.4428,g-ZTF,2026-04-15 08:52:11.003,Fritz,NaN,NaN,2026TNSTR1638....1S,2026TNSCR2000....1F,NaN,NaN

In [53]:
ra = np.array(sources["RA"])
dec = np.array(sources["DEC"])
z = np.array(sources["Redshift"])
supernovaes = []
# for r, d in zip(ra, dec):
#     #print(r, d)
#     coord = SkyCoord(ra=r, dec=d, unit=(u.hourangle, u.deg))
#     supernovae = alerce.query_objects(ra=coord.ra.deg, dec=coord.dec.deg, survey="ztf", format="pandas")
#     supernovaes.append(supernovae)
# supernovaes
#print(ra)

In [39]:
coord = SkyCoord(ra=ra[:, None], dec=dec[:,None], unit=(u.hourangle, u.deg))

In [54]:
#print(coord)

In [58]:
super_ra = coord.ra.deg
super_dec = coord.dec.deg
#print(super_ra)
supernovaes = []
for r, d in zip(super_ra, super_dec):
    # print(r, d)
    supernovae = alerce.query_objects(ra=r, dec=d, survey="ztf", format="pandas")
    supernovaes.append(supernovae)

supernovaes

[            oid ndethist  ncovhist  mjdstarthist    mjdendhist  corrected  \
 0  ZTF20abbcsrb        1       190  58992.230521  58992.230521      False
 1  ZTF20aasibxr       15       659  58912.437465  60458.228958       True
 2  ZTF25aciozba        1      1067  61026.519375  61026.519375       True
 3  ZTF26aauvuig        8      1222  61167.231539  61171.317431      False

    stellar  ndet g_r_max g_r_max_corr  ...       lastmjd   deltajd  \
 0    False     1    None         None  ...  58992.230521  0.000000
 1    False     1    None         None  ...  60458.228958  0.000000
 2    False     1    None         None  ...  61026.519375  0.000000
 3    False     8    None         None  ...  61171.317431  4.085891

        meanra    meandec   sigmara  sigmadec  class  classifier  probability  \
 0  201.654118 -12.104484       NaN       NaN   None        None         None
 1  201.653957 -12.102476  0.066478  0.065000   None        None         None
 2  201.659106 -12.110047  0.086935  0.085000   None        None         None
 3  201.655174 -12.103061  0.026404  0.025817   None        None         None

       step_id_corr
 0  corr_bulk_0.0.1
 1           24.4.1
 2   27.5.7a32.dev1
 3   27.5.7a32.dev1

 [4 rows x 23 columns],
             oid ndethist  ncovhist  mjdstarthist    mjdendhist  corrected  \
 0  ZTF24aallboj        1      1445  60430.338067  60430.338067      False
 1  ZTF24aamfurg        1      1451  60434.369768  60434.369768      False
 2  ZTF20abgnlmd        9      1545  58689.173391  60471.250289       True
 3  ZTF26aauxkmg       13      2014  61167.369410  61171.407037      False
 4  ZTF26aaveuqb        1      2005  61168.424282  61168.424282      False

    stellar  ndet g_r_max g_r_max_corr  ...       lastmjd      deltajd  \
 0    False     1    None         None  ...  60430.338067     0.000000
 1    False     1    None         None  ...  60434.369768     0.000000
 2    False     2    None         None  ...  60471.250289  1451.029838
 3    False    13    None         None  ...  61171.407037     4.037627
 4    False     1    None         None  ...  61168.424282     0.000000

        meanra   meandec   sigmara  sigmadec  class  classifier  probability  \
 0  234.600443  2.837543  0.065080  0.065000   None        None         None
 1  234.603031  2.843610  0.085105  0.085000   None        None         None
 2  234.606085  2.841983  0.065080  0.065000   None        None         None
 3  234.605503  2.841331  0.005608  0.005601   None        None         None
 4  234.601204  2.837098  0.065080  0.065000   None        None         None

      step_id_corr
 0          24.4.1
 1          24.4.1
 2          24.5.1
 3  27.5.7a32.dev1
 4  27.5.7a32.dev1

 [5 rows x 23 columns],
             oid ndethist  ncovhist  mjdstarthist    mjdendhist  corrected  \
 0  ZTF23aaeqqlk        1       525  60044.250000  60044.250000      False
 1  ZTF26aauvdne        9      1343  61167.210741  61171.317905      False

    stellar  ndet g_r_max g_r_max_corr  ...       lastmjd   deltajd  \
 0    False     1    None         None  ...  60044.333599  0.000000
 1    False     9    None         None  ...  61171.317905  4.107164

        meanra   meandec   sigmara  sigmadec  class  classifier  probability  \
 0  202.461350 -5.758274       NaN       NaN   None        None         None
 1  202.457035 -5.751724  0.006877  0.006842   None        None         None

      step_id_corr
 0           1.1.6
 1  27.5.7a32.dev1

 [2 rows x 23 columns],
             oid ndethist  ncovhist  mjdstarthist    mjdendhist  corrected  \
 0  ZTF26aasndyv        2      4036  60977.551759  61145.381505      False
 1  ZTF26aaurvzt       15      4063  61162.250197  61171.331968       True

    stellar  ndet g_r_max g_r_max_corr  ...       lastmjd   deltajd  \
 0    False     1    None         None  ...  61145.381505  0.000000
 1    False    15    None         None  ...  61171.331968  9.081771

        meanra    meandec   sigmara  sigmadec  class  classifier  probability  \
 0  196.904039  15.229393  0.010364  0.010000   None        None         None
 1  196.898665  15.223555  0.009333  0.009005   None        None         None

      step_id_corr
 0  27.5.7a32.dev1
 1  27.5.7a32.dev1

 [2 rows x 23 columns],
 Empty DataFrame
 Columns: []
 Index: [],
             oid ndethist  ncovhist  mjdstarthist    mjdendhist  corrected  \
 0  ZTF19aazsvhq        5       534  58439.551505  59372.192234       True
 1  ZTF21aagypcq        2       397  58999.229410  59249.440174      False
 2  ZTF19adigqqk        9      1074  58439.551505  60355.353530       True
 3  ZTF26aauvgeo       22      2329  61167.187350  61171.319317      False

    stellar  ndet g_r_max g_r_max_corr  ...       lastmjd     deltajd  \
 0    False     3    None         None  ...  59372.192234  722.022326
 1    False     1    None         None  ...  59249.440174    0.000000
 2    False     2    None         None  ...  60355.353530  358.931262
 3    False    22    None         None  ...  61171.319317    4.131968

        meanra    meandec   sigmara  sigmadec  class  classifier  probability  \
 0  192.375613 -11.400988  0.000053  0.000004   None        None         None
 1  192.376040 -11.400846       NaN       NaN   None        None         None
 2  192.375407 -11.400938  0.066308  0.065000   None        None         None
 3  192.371239 -11.403531  0.003356  0.003290   None        None         None

        step_id_corr
 0  correction_0.0.1
 1  correction_0.0.1
 2             1.1.6
 3    27.5.7a32.dev1

 [4 rows x 23 columns],
             oid ndethist  ncovhist  mjdstarthist    mjdendhist  corrected  \
 0  ZTF20abeyrvn        1       180  59014.198461  59014.198461      False
 1  ZTF25aatmudv        1       989  60829.239907  60829.239907      False
 2  ZTF26aauunhp       14      1260  61162.272072  61171.319780       True

    stellar  ndet g_r_max g_r_max_corr  ...       lastmjd   deltajd  \
 0    False     1    None         None  ...  59014.198461  0.000000
 1    False     1    None         None  ...  60829.239907  0.000000
 2    False    14    None         None  ...  61171.319780  9.047708

        meanra   meandec   sigmara  sigmadec  class  classifier  probability  \
 0  188.924497 -4.080604       NaN       NaN   None        None         None
 1  188.934109 -4.088504  0.085217  0.085000   None        None         None
 2  188.928280 -4.084202  0.004899  0.004887   None        None         None

       step_id_corr
 0  corr_bulk_0.0.1
 1           27.5.6
 2   27.5.7a32.dev1

 [3 rows x 23 columns],
             oid ndethist  ncovhist  mjdstarthist    mjdendhist  corrected  \
 0  ZTF19aaokpbo        1       746  58575.340023  58575.340023      False
 1  ZTF21aawfcfe        1      2358  59321.412350  59321.412350      False

    stellar  ndet g_r_max g_r_max_corr  ...       lastmjd deltajd      meanra  \
 0    False     1    None         None  ...  58575.340023     0.0  225.797367
 1    False     1    None         None  ...  59321.412350     0.0  225.804709

      meandec  sigmara  sigmadec  class classifier probability  \
 0  44.374919     None      None   None       None        None
 1  44.369434     None      None   None       None        None

        step_id_corr
 0   corr_bulk_0.0.1
 1  correction_0.0.1

 [2 rows x 23 columns],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
             oid ndethist  ncovhist  mjdstarthist    mjdendhist  corrected  \
 0  ZTF19acrwwef        1        82  58799.482060  58799.482060      False
 1  ZTF26aaunjpq        1      1039  61160.169317  61160.169317      False

    stellar  ndet g_r_max g_r_max_corr  ...       lastmjd deltajd      meanra  \
 0    False     1    None         None  ...  58799.482060     0.0  141.390054
 1    False     1    None         None  ...  61160.169317     0.0  141.394029

      meandec   sigmara  sigmadec  class  classifier  probability  \
 0 -13.953817       NaN       NaN   None        None         None
 1 -13.950042  0.010304      0.01   None        None         None

       step_id_corr
 0  corr_bulk_0.0.1
 1   27.5.7a32.dev1

 [2 rows x 23 columns],
             oid ndethist  ncovhist  mjdstarthist    mjdendhist  corrected  \
 0  ZTF20acnvior        1       415  59149.505382  59149.505382      False
 1  ZTF26aaurnvv       18      1690  61160.219317  61171.285428       True

    stellar  ndet g_r_max g_r_max_corr  ...       lastmjd    deltajd  \
 0    False     1    None         None  ...  59149.505382   0.000000
 1    False    17    None         None  ...  61171.285428  11.066111

        meanra    meandec   sigmara  sigmadec  class  classifier  probability  \
 0  163.923458  15.614354       NaN       NaN   None        None         None
 1  163.917896  15.610357  0.005748  0.005536   None        None         None

       step_id_corr
 0  corr_bulk_0.0.1
 1   27.5.7a32.dev1

 [2 rows x 23 columns],
             oid ndethist  ncovhist  mjdstarthist    mjdendhist  corrected  \
 0  ZTF23aaoiofz        1       983  60112.250000  60112.250000      False
 1  ZTF26aaulhso       15      1716  61159.233738  61171.168218      False

    stellar  ndet g_r_max g_r_max_corr  ...       lastmjd    deltajd  \
 0    False     1    None         None  ...  60112.186273   0.000000
 1    False    15    None         None  ...  61171.168218  11.934479

        meanra   meandec   sigmara  sigmadec  class  classifier  probability  \
 0  150.224602  9.133097       NaN       NaN   None        None         None
 1  150.220475  9.138394  0.005649  0.005577   None        None         None

      step_id_corr
 0           1.2.0
 1  27.5.7a32.dev1

 [2 rows x 23 columns],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
             oid ndethist  ncovhist  mjdstarthist    mjdendhist  corrected  \
 0  ZTF26aaupgtw       25      3400  61159.491956  61171.480741      False

    stellar  ndet g_r_max g_r_max_corr  ...       lastmjd    deltajd  \
 0    False    25    None         None  ...  61171.480741  11.988785

       meanra   meandec   sigmara  sigmadec  class  classifier  probability  \
 0  333.66955  5.080774  0.003729  0.003714   None        None         None

      step_id_corr
 0  27.5.7a32.dev1

 [1 rows x 23 columns],
             oid ndethist  ncovhist  mjdstarthist   mjdendhist  corrected  \
 0  ZTF26aaukgfm        4       996  61159.167894  61167.16265      False

    stellar  ndet g_r_max g_r_max_corr  ...      lastmjd   deltajd      meanra  \
 0    False     4    None         None  ...  61167.16265  7.994757  148.430355

      meandec   sigmara  sigmadec  class  classifier  probability  \
 0 -14.236835  0.005158     0.005   None        None         None

      step_id_corr
 0  27.5.7a32.dev1

 [1 rows x 23 columns],
             oid ndethist  ncovhist  mjdstarthist    mjdendhist  corrected  \
 0  ZTF21aawnqtd        1       373  59323.333021  59323.333021      False
 1  ZTF19aaloljd       18      1466  58543.358090  61171.320255       True

    stellar  ndet g_r_max g_r_max_corr  ...       lastmjd      deltajd  \
 0    False     1    None         None  ...  59323.333021     0.000000
 1    False    17    None         None  ...  61171.320255  2627.962164

        meanra   meandec   sigmara  sigmadec  class  classifier  probability  \
 0  191.297059  3.830920       NaN       NaN   None        None         None
 1  191.294630  3.824884  0.017103  0.017065   None        None         None

        step_id_corr
 0  correction_0.0.1
 1    27.5.7a32.dev1

 [2 rows x 23 columns],
             oid ndethist  ncovhist  mjdstarthist    mjdendhist  corrected  \
 0  ZTF25aadzfvi        1      1201  60708.326713  60708.326713      False
 1  ZTF26aatikbf        1      1582  61150.170903  61150.170903      False
 2  ZTF26aaulhci       15      1603  61159.233738  61171.168218      False

    stellar  ndet g_r_max g_r_max_corr  ...       lastmjd    deltajd  \
 0    False     1    None         None  ...  60708.326713   0.000000
 1    False     1    None         None  ...  61150.170903   0.000000
 2    False    15    None         None  ...  61171.168218  11.934479

        meanra   meandec   sigmara  sigmadec  class  classifier  probability  \
 0  153.065354  9.279384  0.065862  0.065000   None        None         None
 1  153.069879  9.283926  0.086128  0.085000   None        None         None
 2  153.064420  9.282505  0.005651  0.005577   None        None         None

      step_id_corr
 0          26.0.1
 1  27.5.7a32.dev1
 2  27.5.7a32.dev1

 [3 rows x 23 columns],
 Empty DataFrame
 Columns: []
 Index: [],
             oid ndethist  ncovhist  mjdstarthist    mjdendhist  corrected  \
 0  ZTF25aateyvv       11       992  59305.272396  61170.171933       True

    stellar  ndet g_r_max g_r_max_corr  ...       lastmjd    deltajd  \
 0    False     9    None         None  ...  61170.171933  10.982303

        meanra    meandec   sigmara  sigmadec  class  classifier  probability  \
 0  164.921079 -10.693696  0.006979  0.006858   None        None         None

      step_id_corr
 0  27.5.7a32.dev1

 [1 rows x 23 columns],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
             oid ndethist  ncovhist  mjdstarthist    mjdendhist  corrected  \
 0  ZTF26aaumtdl       16      1145  61158.395914  61171.426898       True

    stellar  ndet g_r_max g_r_max_corr  ...       lastmjd    deltajd  \
 0    False    16    None         None  ...  61171.426898  13.030984

        meanra    meandec  sigmara  sigmadec  class  classifier  probability  \
 0  242.956779 -12.334239    0.019  0.018562   None        None         None

      step_id_corr
 0  27.5.7a32.dev1

 [1 rows x 23 columns],
             oid ndethist  ncovhist  mjdstarthist    mjdendhist  corrected  \
 0  ZTF25aadqzkn        1      1533  60707.398241  60707.398241      False
 1  ZTF25aadrrxi        1      1535  60707.421574  60707.421574      False
 2  ZTF25aadsfvh        1      1539  60707.444965  60707.444965      False
 3  ZTF25aaeangx        1      1535  60708.352222  60708.352222      False
 4  ZTF26aaulhlc       15      2050  61154.170799  61170.208299      False

    stellar  ndet g_r_max g_r_max_corr  ...       lastmjd  deltajd      meanra  \
 0    False     1    None         None  ...  60707.398241   0.0000  148.332264
 1    False     1    None         None  ...  60707.421574   0.0000  148.329562
 2    False     1    None         None  ...  60707.444965   0.0000  148.326790
 3    False     1    None         None  ...  60708.352222   0.0000  148.325473
 4    False    15    None         None  ...  61170.208299  16.0375  148.331170

     meandec   sigmara  sigmadec  class  classifier  probability  \
 0  7.973811  0.085830  0.085000   None        None         None
 1  7.975175  0.065635  0.065000   None        None         None
 2  7.976220  0.085830  0.085000   None        None         None
 3  7.967765  0.085829  0.085000   None        None         None
 4  7.972097  0.005631  0.005577   None        None         None

      step_id_corr
 0          26.0.1
 1          26.0.1
 2          26.0.1
 3          26.0.1
 4  27.5.7a32.dev1

 [5 rows x 23 columns],
             oid ndethist  ncovhist  mjdstarthist    mjdendhist  corrected  \
 0  ZTF26aatuoje       84      1264  61153.185903  61170.233866      False

    stellar  ndet g_r_max g_r_max_corr  ...       lastmjd    deltajd  \
 0    False    13    None         None  ...  61170.233866  16.937905

        meanra    meandec   sigmara  sigmadec  class  classifier  probability  \
 0  171.981408 -13.649302  0.005755  0.005592   None        None         None

      step_id_corr
 0  27.5.7a32.dev1

 [1 rows x 23 columns],
             oid ndethist  ncovhist  mjdstarthist    mjdendhist  corrected  \
 0  ZTF18acqezwe        1       114  58442.383449  58442.383449      False
 1  ZTF22aabsnos        1      1032  59636.228854  59636.228854      False
 2  ZTF26aatidrh        9      1860  61087.245266  61162.163102      False

    stellar  ndet g_r_max g_r_max_corr  ...       lastmjd    deltajd  \
 0    False     1    None         None  ...  58442.383449   0.000000
 1    False     1    None         None  ...  59636.228854   0.000000
 2    False     8    None         None  ...  61162.163102  12.976343

        meanra    meandec   sigmara  sigmadec  class  classifier  probability  \
 0  136.848478  12.399338       NaN       NaN   None        None         None
 1  136.844914  12.398771       NaN       NaN   None        None         None
 2  136.850287  12.403345  0.007028  0.006864   None        None         None

        step_id_corr
 0   corr_bulk_0.0.1
 1  correction_1.0.6
 2    27.5.7a32.dev1

 [3 rows x 23 columns],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
             oid ndethist  ncovhist  mjdstarthist    mjdendhist  corrected  \
 0  ZTF26aausykz        3      1719  61162.476389  61171.475729      False

    stellar  ndet g_r_max g_r_max_corr  ...       lastmjd  deltajd      meanra  \
 0    False     3    None         None  ...  61171.475729  8.99934  312.494883

      meandec   sigmara  sigmadec  class  classifier  probability  \
 0 -19.632424  0.010424  0.009818   None        None         None

      step_id_corr
 0  27.5.7a32.dev1

 [1 rows x 23 columns],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
             oid ndethist  ncovhist  mjdstarthist    mjdendhist  corrected  \
 0  ZTF26aaunkyk        2      1188   61159.16978  61160.172141      False

    stellar  ndet g_r_max g_r_max_corr  ...       lastmjd   deltajd  \
 0    False     2    None         None  ...  61160.172141  1.002361

        meanra    meandec   sigmara  sigmadec  class  classifier  probability  \
 0  133.822031 -14.524302  0.007305  0.007071   None        None         None

      step_id_corr
 0  27.5.7a32.dev1

 [1 rows x 23 columns],
             oid ndethist  ncovhist  mjdstarthist    mjdendhist  corrected  \
 0  ZTF26aaudaac       23      2024  61150.457326  61171.427373      False

    stellar  ndet g_r_max g_r_max_corr  ...       lastmjd    deltajd  \
 0    False    23    None         None  ...  61171.427373  20.970046

        meanra   meandec   sigmara  sigmadec  class  classifier  probability  \
 0  247.293429  0.810905  0.005436  0.005435   None        None         None

      step_id_corr
 0  27.5.7a32.dev1

 [1 rows x 23 columns],
             oid ndethist  ncovhist  mjdstarthist    mjdendhist  corrected  \
 0  ZTF25aanygdi        1      5192  60787.407627  60787.407627      False

    stellar  ndet g_r_max g_r_max_corr  ...       lastmjd deltajd      meanra  \
 0    False     1    None         None  ...  60787.407627     0.0  251.685683

      meandec   sigmara  sigmadec  class  classifier  probability step_id_corr
 0  49.035044  0.099146     0.065   None        None         None       26.0.1

 [1 rows x 23 columns],
             oid ndethist  ncovhist  mjdstarthist    mjdendhist  corrected  \
 0  ZTF20abbsypw        1       280  58995.254097  58995.254097      False
 1  ZTF19adhqvhn        5      1427  58469.500000  60172.250000       True
 2  ZTF26aaubove       27      2265  61154.326690  61171.353924      False

    stellar  ndet   g_r_max  g_r_max_corr  ...       lastmjd    deltajd  \
 0    False     1       NaN           NaN  ...  58995.254097   0.000000
 1    False     5  2.563448      1.827192  ...  60172.173403  87.836354
 2    False    27       NaN           NaN  ...  61171.353924  17.027234

        meanra   meandec   sigmara  sigmadec  class  classifier  probability  \
 0  224.501023  5.470521       NaN       NaN   None        None         None
 1  224.509843  5.467779  0.000119  0.000062   None        None         None

In [60]:
supernovaes[np.where(supernovaes, None)]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (100,) + inhomogeneous part.